cold_storage:
- ' '
design: design.tsv
fasta: /home/tdayris/Documents/Developpement/tdayris-perso/bam-msisensor/tests/example.fa
params:
  msi_extra: ''
  msi_scan_extra: ''
singularity_docker_image: docker://continuumio/miniconda3:4.4.10
threads: 1
workdir: /home/tdayris/Documents/Developpement/tdayris-perso/bam-msisensor/tests
